### ISSUE TITLE
Unable to run or use PrivacyRaven in Colab

### ISSUE THREAD

**Issue by ksasi** [trailofbits/PrivacyRaven#51]
Hi,

It appears due to the use of poetry to enforce dependencies and create virtualenv for PrivacyRaven, we are unable to use this in google colab or jupyter notebook environments. Please suggest a work around or alternative for the same.

Thanks and Regards,
Sasikanth

**Comment by suhacker1** [comment]
Hi! Thank you for pointing this out! 

I was able to get Jupyter Notebook working with PrivacyRaven after adding it as a poetry dependency and then running `poetry shell` followed by `jupyter notebook` (this also works with Jupyter Lab). Google Colab runs on an older, unsupported version of Python, but I'll add Python 3.6 to the current setup. With a 3.8 kernel, this should help:

```
!git clone https://github.com/trailofbits/PrivacyRaven.git
!pip install poetry
%cd PrivacyRaven
!poetry install
```

We will be having a pip release soon, which will eliminate the extra steps. I'll make sure to include this fix in my next PR to PrivacyRaven. Thanks again!
