### ISSUE TITLE
Add support for Python 3.6, 3.8, and 3.9

### ISSUE THREAD

**Issue by suhacker1** [trailofbits/PrivacyRaven#52]
**Is your feature request related to a problem? Please describe.**
Presently, PrivacyRaven supports 3.7. Supporting 3.6 specifically would enable PrivacyRaven to work on Google Colab.

**Describe the solution you'd like.**
Minimal changes to existing code is preferred. 

**Describe alternatives you've considered.**
Forcing Colab to run on a 3.8 kernel would increase the complexity of getting started with PrivacyRaven. 

**Detail any additional context.**
This is in response to #51.

**Comment by pwang00** [comment]
I'll be looking into this and seeing if I can get PrivacyRaven / Poetry to work inside a Python 3.6.10 Docker container.
